In [29]:
import numpy as np
import matplotlib.pyplot as plt

Backwards Time Centered Space Implicit Method

In [30]:
D = 1 # Diffusivity
time_step = 0.1
step_size = 0.1

In [31]:
r = (D * time_step) / (step_size**2)
r

9.999999999999998

In [32]:
2 * r + 1

20.999999999999996

In [33]:
x_range = np.arange(0, 1 + step_size, step_size)
t_range = np.arange(0, 1 + time_step, time_step)

In [34]:
x_len, t_len = len(x_range), len(t_range)

In [35]:
first_diag = np.array([-r] * (x_len - 1))
first_diag.T

array([-10., -10., -10., -10., -10., -10., -10., -10., -10., -10.])

In [36]:
second_diag = np.array([2*r + 1] * x_len)
second_diag.T

array([21., 21., 21., 21., 21., 21., 21., 21., 21., 21., 21.])

In [39]:
A = np.diag(second_diag, k = 0) + np.diag(first_diag, k = -1) + np.diag(first_diag, k = 1)
A

array([[ 21., -10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [-10.,  21., -10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., -10.,  21., -10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0., -10.,  21., -10.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10.,  21., -10.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., -10.,  21., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., -10.,  21., -10.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0., -10.,  21., -10.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., -10.,  21., -10.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -10.,  21., -10.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -10.,  21.]])